---
- hosts: all
  become: yes
  become_user: root
  become_method: su
  tasks:
   - name: "Installing Docker Prerequisite packages"
     yum:
      name: ['yum-utils','device-mapper-persistent-data','lvm2']
      state: latest
     when: ansible_distribution == 'CentOS'
   - name: "Configuring docker-ce repo"
     get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644
     when: ansible_distribution == 'CentOS'
   - name: " Installing Docker latest version"
     yum:
       name: docker-ce
       state: present
     when: ansible_distribution == 'CentOS'
   - name: " Starting and Enabling Docker service"
     service:
      name: docker
      state: started
      enabled: yes
     when: ansible_distribution == 'CentOS'
    
   - name: Add Docker GPG key
     apt_key: url=https://download.docker.com/linux/ubuntu/gpg
     when: ansible_distribution == 'Ubuntu'


   - name: Add Docker APT repository
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
     when: ansible_distribution == 'Ubuntu'

   - name: Install list of packages
     apt:
      name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
      state: present
      update_cache: yes
     when: ansible_distribution == 'Ubuntu'

