---

#Docker related Tasks
   - name: "Installing Docker Prerequisite packages"
     yum:
      name: '{{centos_docker_packages}}'
      state: present
     tags:
      - docker
   - name: "Configuring docker-ce repo"
     get_url:
      url: '{{centos_docker_repo}}'
      dest: '{{centos_docker_location}}'
      mode: '{{centos_docker_get_mode}}'
     tags:
      - docker
   - name: "Installing Docker latest version"
     yum:
       name: '{{centos_docker_ce}}'
       state: present
     tags:
      - docker
   - name: "Starting and Enabling Docker service"
     service:
      name: '{{centos_docker_service}}'
      state: started
      enabled: yes
     tags:
      - docker


#Docker-Compose related  Tasks
   - name: "Ensure docker-compose is installed and available"
     get_url: 
      url : '{{centos_docker_compose_url}}-{{ ansible_system }}-{{ ansible_userspace_architecture }}'
      dest: '{{docker_compose_location}}'
      mode: '{{docker_compose_get_mode}}'
     tags:
      - docker_compose
   - name: "Install Docker Compose"
     yum:
      name: '{{docker_compose}}'
      state: present
     tags:
      - docker_compose
   
   
