---
# tasks file for install_docker
- import_tasks: install_docker_centos.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: install_docker_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

