---


# User Creation related Tasks 
    - name: Create a new User
      user: 'name={{docker_user}} append=yes state=present createhome=yes shell={{shell_path}}'
      tags:
       - create_user

    - name: Allow user to have passwordless sudo
      lineinfile:
        dest: '{{sudoers_path}}'
        line: '{{docker_user}} ALL=(ALL) NOPASSWD: ALL'
      tags:
       - create_user        

    - name: Set up authorized keys for the new user
      authorized_key:
       user='{{docker_user}}'
       key="{{item}}"
      with_file:
       - '{{ssh_file_path}}'
      tags:
       - create_user



# Adding New User to Docker Group related Tasks
    - name: Create Docker group
      group:
       name: '{{docker_group}}'
       state: present
      tags:
       - docker_group

    - name: Add new User to Docker Group
      user:
       name: '{{docker_user}}'
       groups: '{{docker_group}}'
       append: yes
      tags:
       - docker_group

